swagger: '2.0'

info:
  version: "1.0"
  title: fhir bundle generator
  description: Generate fhir bundles

schemes:
  - https
  - http

basePath: /v1

paths:
  /bundleConverter/convert:
    post:
      operationId: bundleConverter
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: searchSet
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Return the json bundle
          schema:
            type: string
        "500":
          description: Error / Exception
  /getBundle:
    get:
      operationId: getBundle
      produces:
        - application/json
      parameters:
        - in: query
          name: patientId
          required: true
          schema:
            type: string
        - in: query
          name: familyName
          required: true
          schema:
            type: string
        - in: query
          name: numReps
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Return Fhir bundle
          schema:
            type: string
        "500":
          description: Error / Exception