swagger: '2.0'

info:
  version: "1.0"
  title: fhir bundle converter api
  description: Convert searchset bundle to transaction

schemes:
  - https
  - http

basePath: /v1

paths:
  /bundleConverter/convert:
    post:
      operationId: searchset2transaction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: searchSet
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Return the json bundle
          schema:
            type: string
        "500":
          description: Error / Exception
  /getBundle:
    get:
      operationId: getBundle
      produces:
        - application/json
      parameters:
        - in: query
          name: patientId
          required: true
          schema:
            type: string
        - in: query
          name: patientName
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Return Fhir bundle
          schema:
            type: string
        "500":
          description: Error / Exception